type User = {
  _id: number;
  firstName: string;
  lastName: string;
  email: string;
  address: string;
  phone: string;
  status: boolean;
};

export const users: User[] = [
  {
    _id: 1,
    firstName: "Abu Bakar",
    lastName: "Siddik",
    email: "abubakar@gmail.com",
    address: "Makkah, Saudi Arabia",
    phone: "01715676545453415",
    status: true,
  },
  {
    _id: 2,
    firstName: "Abu Bakar",
    lastName: "Siddik",
    email: "abubakar@gmail.com",
    address: "Makkah, Saudi Arabia",
    phone: "01715676545453415",
    status: true,
  },
  {
    _id: 3,
    firstName: "Abu Bakar",
    lastName: "Siddik",
    email: "abubakar@gmail.com",
    address: "Makkah, Saudi Arabia",
    phone: "01715676545453415",
    status: true,
  },
  {
    _id: 4,
    firstName: "Abu Bakar",
    lastName: "Siddik",
    email: "abubakar@gmail.com",
    address: "Makkah, Saudi Arabia",
    phone: "01715676545453415",
    status: true,
  },
  {
    _id: 5,
    firstName: "Abu Bakar",
    lastName: "Siddik",
    email: "abubakar@gmail.com",
    address: "Makkah, Saudi Arabia",
    phone: "01715676545453415",
    status: true,
  },
  {
    _id: 6,
    firstName: "Abu Bakar",
    lastName: "Siddik",
    email: "abubakar@gmail.com",
    address: "Makkah, Saudi Arabia",
    phone: "01715676545453415",
    status: true,
  },
  {
    _id: 7,
    firstName: "Abu Bakar",
    lastName: "Siddik",
    email: "abubakar@gmail.com",
    address: "Makkah, Saudi Arabia",
    phone: "01715676545453415",
    status: true,
  },
  {
    _id: 8,
    firstName: "Abu Bakar",
    lastName: "Siddik",
    email: "abubakar@gmail.com",
    address: "Makkah, Saudi Arabia",
    phone: "01715676545453415",
    status: true,
  },
  {
    _id: 9,
    firstName: "Abu Bakar",
    lastName: "Siddik",
    email: "abubakar@gmail.com",
    address: "Makkah, Saudi Arabia",
    phone: "01715676545453415",
    status: true,
  },
  {
    _id: 10,
    firstName: "Abu Bakar",
    lastName: "Siddik",
    email: "abubakar@gmail.com",
    address: "Makkah, Saudi Arabia",
    phone: "01715676545453415",
    status: true,
  },
  {
    _id: 11,
    firstName: "Abu Bakar",
    lastName: "Siddik",
    email: "abubakar@gmail.com",
    address: "Makkah, Saudi Arabia",
    phone: "01715676545453415",
    status: true,
  },
  {
    _id: 12,
    firstName: "Abu Bakar",
    lastName: "Siddik",
    email: "abubakar@gmail.com",
    address: "Makkah, Saudi Arabia",
    phone: "01715676545453415",
    status: true,
  },
  {
    _id: 13,
    firstName: "Abu Bakar",
    lastName: "Siddik",
    email: "abubakar@gmail.com",
    address: "Makkah, Saudi Arabia",
    phone: "01715676545453415",
    status: true,
  },
  {
    _id: 14,
    firstName: "Abu Bakar",
    lastName: "Siddik",
    email: "abubakar@gmail.com",
    address: "Makkah, Saudi Arabia",
    phone: "01715676545453415",
    status: true,
  },
];
